# https://help.github.com/en/articles/metadata-syntax-for-github-actions
name: 'Docker scout'
description: 'Check vulnerabilities'

inputs:
  command:
    description: 'actions to be performed'
    default: 'cves'
    required: true
  version:
    description: 'Docker scout version'
    default: 'latest'
    required: true
  format:
    description: 'Output format'
    default: 'packages'
    required: true
  image:
    description: 'Name of the image'
    required: true
  output-file:
    description: 'whether the program outputs a file at all'
    default: false
    required: false

outputs:
  result-file:
    description: 'File output result'
    value: ${{ steps.run.outputs.result-file }}

runs:
  using: node24
  main: index.js